---
    - hosts: all
      become: yes
      tasks:
      - name: Update the package cache if older than 30 minutes
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 1800
      - name: Upgrade all packages to latest
        ansible.builtin.apt:
          name: "*"
          state: latest
      - name: Remove orphaned/old dependencies
        ansible.builtin.apt:
          autoremove: yes
      - name: Run clean to remove cached packages
        apt:
          clean: yes
...